config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "sp_payments#index"

  resources :sp_payments do
    resources :comments,only: :create
  end
  resources :users,only: :show
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

belongs_to :user
belongs_to :sp_payment

validates :text,presence: true

end

app/models/day.rb
class Day < ActiveHash::Base
  self.data = [
    { id: 1, name: '日' },
    { id: 2, name: '1日' },
    { id: 3, name: '2日' },
    { id: 4, name: '3日' },
    { id: 5, name: '4日' },
    { id: 6, name: '5日' },
    { id: 7, name: '6日' },
    { id: 8, name: '7日' },
    { id: 9, name: '8日' },
    { id: 10, name: '9日' },
    { id: 11, name: '10日' },
    { id: 12, name: '11日' },
    { id: 13, name: '12日' },
    { id: 14, name: '13日' },
    { id: 15, name: '14日' },
    { id: 16, name: '15日' },
    { id: 17, name: '16日' },
    { id: 18, name: '17日' },
    { id: 19, name: '18日' },
    { id: 20, name: '19日' },
    { id: 21, name: '20日' },
    { id: 22, name: '21日' },
    { id: 23, name: '22日' },
    { id: 24, name: '23日' },
    { id: 25, name: '24日' },
    { id: 26, name: '25日' },
    { id: 27, name: '26日' },
    { id: 28, name: '27日' },
    { id: 29, name: '28日' },
    { id: 30, name: '29日' },
    { id: 31, name: '30日' },
    { id: 32, name: '31日' }
  ]

  include ActiveHash::Associations
  has_many :sp_payments
end

app/models/kisyu.rb
class Kisyu < ActiveHash::Base
  self.data = [
    { id: 1, name: '機種' },
    { id: 2, name: 'マイジャグ４' },
    { id: 3, name: 'マイジャグ３' },
    { id: 4, name: 'GOジャグ２' },
    { id: 5, name: 'リゼロ' },
    { id: 6, name: 'バジ絆２' },
    { id: 7, name: 'タイバニ' },
    { id: 8, name: '北斗転生' },
    { id: 9, name: 'エウレカ７' },
    { id: 10, name: 'まど２' },
    { id: 11, name: 'まど３' },
    { id: 12, name: '吉宗' },
    { id: 13, name: '番長３' }
  ]

  include ActiveHash::Associations
  has_many :sp_payments
end

app/models/month.rb
class Month < ActiveHash::Base
  self.data = [
    { id: 1, name: '月' },
    { id: 2, name: '1月' },
    { id: 3, name: '2月' },
    { id: 4, name: '3月' },
    { id: 5, name: '4月' },
    { id: 6, name: '5月' },
    { id: 7, name: '6月' },
    { id: 8, name: '7月' },
    { id: 9, name: '8月' },
    { id: 10, name: '9月' },
    { id: 11, name: '10月' },
    { id: 12, name: '11月' },
    { id: 13, name: '12月' }
  ]

  include ActiveHash::Associations
  has_many :sp_payments
end

app/models/prate.rb
class Prate < ActiveHash::Base
  self.data = [
    { id: 1, name: 'P換金率' , rate:'1'},
    { id: 2, name: '28玉交換' , rate:'3.57'},
    { id: 3, name: 'なし' , rate:'1'}
  ]

  include ActiveHash::Associations
  has_many :sp_payments
end

app/models/sp_payment.rb
class SpPayment < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :store
  belongs_to :kisyu
  belongs_to :month
  belongs_to :day
  belongs_to :srate
  belongs_to :prate




  with_options presence: true do
    validates :month_id,:day_id,:store_id,:kisyu_id,:prate_id,:srate_id, numericality: { other_than: 1 }
    validates :investment_medal, format: { with: /\A[0-9]+\z/ , message: "with a half size number"}
    validates :investment_ball, format: { with: /\A[0-9]+\z/ , message: "with a half size number"}
    validates :recovery_medal, format: { with: /\A[0-9]+\z/ , message: "with a half size number"}
    validates :recovery_ball, format: { with: /\A[0-9]+\z/ , message: "with a half size number"}
    validates :medal, format: { with: /\A[-]?[0-9]+(\.[0-9]+)?\z/ , message: "with a half size number"}
    validates :ball, format: { with: /\A[-]?[0-9]+(\.[0-9]+)?\z/ , message: "with a half size number"}
    validates :memo
  end

  belongs_to :user
  has_many :comments
end

app/models/srate.rb
class Srate < ActiveHash::Base
  self.data = [
    { id: 1, name: 'S換金率' ,rate: '1'},
    { id: 2, name: '56枚交換' ,rate: '17.85'},
    { id: 3, name: '51.52枚交換' ,rate: '19.41'},
    { id: 4, name: '47枚交換' ,rate: '21.27'},
    { id: 5, name: 'なし' , rate:'1'}
  ]

  include ActiveHash::Associations
  has_many :sp_payments
end

app/models/store.rb
class Store < ActiveHash::Base
  self.data = [
    { id: 1, name: '稼働店舗' },
    { id: 2, name: '梅田123+N' },
    { id: 3, name: 'マルハン梅田' },
    { id: 4, name: '大東洋梅田' },
    { id: 5, name: '梅田CLUB-D' },
    { id: 6, name: '123難波' },
    { id: 7, name: '楽園難波' },
    { id: 8, name: 'テキサス門真' }
  ]

  include ActiveHash::Associations
  has_many :sp_payments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :nickname,presence: true

         has_many :sp_payments
         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:index, :show]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create

  @comment=Comment.create(comment_params)
  #@user=comment.user
  #render json:{post:@comment,user:@user}
  redirect_to "/sp_payments/#{@comment.sp_payment.id}"

  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id:current_user.id, sp_payment_id:params[:sp_payment_id])
  end

end

app/controllers/sp_payments_controller.rb
class SpPaymentsController < ApplicationController

  def index
    @sp_payments=SpPayment.includes(:user).order("id DESC")
  end

  def new
    @sp_payment=SpPayment.new
  end

  def create
    @sp_payment=SpPayment.new(payment_params)
    if @sp_payment.save
      redirect_to root_path
    else
      render :new
      @sp_payment=SpPayment.new(payment_params)
    end
  end

  def show
    @sp_payment=SpPayment.find(params[:id])
    @comment = Comment.new
    @comments = @sp_payment.comments.includes(:user)
  end

  def destroy
    @sp_payment=SpPayment.find(params[:id])
    if current_user.id==@sp_payment.user_id
      @sp_payment.delete
      redirect_to root_path
    else
      render :show
      @sp_payment=SpPayment.find(params[:id])
    end
  end

  def edit
    @sp_payment=SpPayment.find(params[:id])
    unless current_user.id==@sp_payment.user_id
      redirect_to action: :show
    end
  end

  def update
    @sp_payment=SpPayment.find(params[:id])
    if @sp_payment.update(payment_params)
      redirect_to action: :show
    else
      render :edit
      @sp_payment=SpPayment.find(params[:id])
    end
  end


  private
  def payment_params
    params.require(:sp_payment).permit(:store_id, :kisyu_id, :investment_medal, :investment_ball, :recovery_medal, :recovery_ball, :medal, :srate_id, :prate_id, :ball, :month_id, :day_id, :memo).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

def show
  @user=User.find(params[:id])
  @sp_payments=@user.sp_payments.order("id DESC")
  if current_user.id!=@user.id
    redirect_to root_path
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sp_payments_helper.rb
module SpPaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OneSlotPayment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header> 
      <div class = "header-logo">
        <h1 class = "header-name">Payment</h1>
      </div>
      <%if user_signed_in?%>
      <div class = "header-lists">
        <div class = "header-list">
          <%= link_to 'マイページ', user_path(current_user.id), class:"link" %>
        </div>
        <div class = "header-list">
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete,class:"link" %>
        </div>
      </div>
      <%else%>
      <div class = "header-lists">
        <div class = "header-list">
          <%= link_to 'ログイン', new_user_session_path, class:"link" %>
        </div>
        <div class = "header-list">
          <%= link_to '新規登録', new_user_registration_path, class:"link" %>
        </div>
      </div>
      <%end%>
    </header>
    <%= yield %>
    <footer>
      <div>
        <h3 class = "footer-logo">Payment</h3>
      </div>
    </footer>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/sp_payments/edit.html.erb
<div class = "main">
  <div class = "new-btn">
    <%= link_to 'TOP', root_path, class:"link-new" %>
  </div>

  <div class="form">
      <%= form_with model: @sp_payment,url:sp_payment_path, local: true do |form| %>
      
      <%= render 'shared/error_messages', model: form.object %>
      

      
       <h3 class="new-title">結果入力</h3>
       <div>
        <%= form.collection_select(:store_id, Store.all, :id, :name, {}, {class:"store-select"}) %>
        </div>
        
        <div>
        <%= form.collection_select(:kisyu_id, Kisyu.all, :id, :name, {}, {class:"store-select"}) %>
       </div>


        <div>
        <%= form.text_field :investment_medal, placeholder: "投資メダル" ,class:"items-text"%>
        </div>
        <div>
        <%= form.text_field :investment_ball, placeholder: "投資玉" ,class:"items-text"%>
        </div>
        <div>
        <%= form.text_field :recovery_medal, placeholder: "回収メダル" ,class:"items-text"%>
        </div>
        <div>
        <%= form.text_field :recovery_ball, placeholder: "回収玉" ,class:"items-text"%>
        </div>
        <div>
        <%= form.text_field :medal, placeholder: "メダル収支" ,class:"items-text"%>
        </div>
        <div>
        <%= form.text_field :ball, placeholder: "玉収支" ,class:"items-text"%>
        </div>
        <div>
        <%= form.collection_select(:srate_id, Srate.all, :id, :name, {}, {class:"store-select"}) %>
        </div>
        <div>
        <%= form.collection_select(:prate_id, Prate.all, :id, :name, {}, {class:"store-select"}) %>
        </div>
        <div>
        <%= form.text_area :memo, placeholder: "メモ", rows: "10" ,class:"items-texts"%>
        </div>
        <div>
        <%= form.collection_select(:month_id, Month.all, :id, :name, {}, {class:"store-select"}) %>
        </div>
        <div>
        <%= form.collection_select(:day_id, Day.all, :id, :name, {}, {class:"store-select"}) %>
        </div>
        <div>
        <%= form.submit "SEND" ,class:"store-select"%>
        </div>
      <% end %>
    </div>


</div>

app/views/sp_payments/index.html.erb
<div class="main">
  <div class = "main-head">
    <div class = "new-btn">
      <%= link_to '結果作成', new_sp_payment_path, class:"link-new" %>
    </div>
  </div>
  <div class = "main-contents">
    <%@sp_payments.each do |sp_payment|%>
      <div class = "main-content">
        <div class="content-day">
          <%=sp_payment.month.name%>
          <%=sp_payment.day.name %>
          
        </div>
        <%if sp_payment.medal!="0"%>
        <div class="comtent-medal">
          <%="#{sp_payment.medal}枚"%>
        </div>
        <%end%>
        <%if sp_payment.ball!="0"%>
        <div class="comtent-ball">
          <%="#{sp_payment.ball}玉"%>
        </div>
        <%end%>
        <div class="btns">
        <%= link_to '詳細', sp_payment_path(sp_payment.id),  id:'btn',class: 'btn' %>
        </div>
        
      </div>
      
    <%end%>
  </div>
</div>

app/views/sp_payments/new.html.erb
<div class = "main">
  <div class = "new-btn">
    <%= link_to 'TOP', root_path, class:"link-new" %>
  </div>

  <div class="form">
      <%= form_with model: @sp_payment,url:sp_payments_path, local: true do |form| %>
      
      <%= render 'shared/error_messages', model: form.object %>
      

      
       <h3 class="new-title">結果入力</h3>
       <div>
        <%= form.collection_select(:store_id, Store.all, :id, :name, {}, {class:"store-select"}) %>
        </div>
        
        <div>
        <%= form.collection_select(:kisyu_id, Kisyu.all, :id, :name, {}, {class:"store-select"}) %>
       </div>


        <div>
        <%= form.text_field :investment_medal, placeholder: "投資メダル" ,class:"items-text"%>
        </div>
        <div>
        <%= form.text_field :investment_ball, placeholder: "投資玉" ,class:"items-text"%>
        </div>
        <div>
        <%= form.text_field :recovery_medal, placeholder: "回収メダル" ,class:"items-text"%>
        </div>
        <div>
        <%= form.text_field :recovery_ball, placeholder: "回収玉" ,class:"items-text"%>
        </div>
        <div>
        <%= form.text_field :medal, placeholder: "メダル収支" ,class:"items-text"%>
        </div>
        <div>
        <%= form.text_field :ball, placeholder: "玉収支" ,class:"items-text"%>
        </div>
        <div>
        <%= form.collection_select(:srate_id, Srate.all, :id, :name, {}, {class:"store-select"}) %>
        </div>
        <div>
        <%= form.collection_select(:prate_id, Prate.all, :id, :name, {}, {class:"store-select"}) %>
        </div>
        <div>
        <%= form.text_area :memo, placeholder: "メモ", rows: "10" ,class:"items-texts"%>
        </div>        
        <div>
        <%= form.collection_select(:month_id, Month.all, :id, :name, {}, {class:"store-select"}) %>
        </div>
        <div>
        <%= form.collection_select(:day_id, Day.all, :id, :name, {}, {class:"store-select"}) %>
        </div>
        <div>
        <%= form.submit "SEND" ,class:"store-select"%>
        </div>
      <% end %>
    </div>


</div>

app/views/sp_payments/show.html.erb
<div class="main">
  <div class="btn3">
    <div class = "new-btn">
      <%= link_to 'TOP', root_path, class:"link-new" %>
    </div>
    <%if user_signed_in?&&current_user.id==@sp_payment.user_id%>
    <div class = "new-btns">
      <%= link_to '編集', edit_sp_payment_path(@sp_payment.id), class:"link-new" %>
      <%= link_to '削除', sp_payment_path(@sp_payment.id), method: :delete, class:"link-new" %>
    </div>
    <%end%>
  </div>

  <div class="show-day">
    <%=@sp_payment.month.name%>
    <%=@sp_payment.day.name%>
  </div>
  <div class="show-day">
    <%="店名   #{@sp_payment.store.name}"%>
  </div>
  <div class="show-day">
    <%="機種   #{@sp_payment.kisyu.name}"%>
  </div>
  <%if @sp_payment.medal!="0"&&@sp_payment.investment_medal!="0"&&@sp_payment.recovery_medal!="0"%>
  <div class="show-day">
    <%="投資メダル   #{@sp_payment.investment_medal}枚"%>
  </div>
  <div class="show-day">
    <%="回収メダル   #{@sp_payment.recovery_medal}枚"%>
  </div>
  <div class="show-day">
    <%="メダル収支   #{@sp_payment.medal}枚"%>
  </div>
  <%end%>
  <%if @sp_payment.ball!="0"&&@sp_payment.investment_ball!="0"&&@sp_payment.recovery_ball!="0"%>
  <div class="show-day">
    <%="投資玉   #{@sp_payment.investment_ball}玉"%>
  </div>
  <div class="show-day">
    <%="回収玉   #{@sp_payment.recovery_ball}玉"%>
  </div>
  <div class="show-day">
    <%="玉収支   #{@sp_payment.ball}玉"%>
  </div>
  <%end%>
  <div class="show-day">
    金額換算
    <%=(@sp_payment.medal.to_i*@sp_payment.srate.rate.to_i+@sp_payment.ball.to_i*@sp_payment.prate.rate.to_i).to_i%>
    円
  </div>
  <div class="show-day">
    メモ
  </div>

  <div class="show-day">
    <%= @sp_payment.memo%>
  </div>

  <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@sp_payment, @comment],id: 'form', local: true) do |form| %>
      <div>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2", id: "content" ,class:"items-texts"%>
        </div>
        <div>
        <%= form.submit "SEND" ,class:"store-select", id:"submit"%>
        </div>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
  </div>
  <div id="list">
  </div>
   <div class="show-day">
    <% @comments.each do |comment| %>
        <div class="ppp" data-id=<%=comment.sp_payment_id%>>
          <strong><%=comment.user.nickname%>：</strong>
          <%= comment.text %>
        </div>
      <% end %>
   
   </div>
  



</div>

app/views/users/show.html.erb
<div class="main">
  <div class = "new-btn">
    <%= link_to 'TOP', root_path, class:"link-new" %>
  </div>
  <div class = "main-head">
    <div class = "new-btn">
      <%= link_to '結果作成', new_sp_payment_path, class:"link-new" %>
    </div>
    <div class = "totals">
      <div class="show-day">
      <%="総メダル数 #{@sp_payments.sum(:medal).to_i}枚"%>
      </div>
      <div class="show-day">
      <%="総玉数 #{@sp_payments.sum(:ball).to_i}玉"%>
      </div>
      <div class="show-day">
      Total収支 <%=(@sp_payments.sum(:medal).to_i*19.5+@sp_payments.sum(:ball).to_i*3.57).to_i%>円
      </div>
    </div>
  </div>
  <div class = "main-contents">
    <%@sp_payments.each do |sp_payment|%>
      <div class = "main-content">
        <div class="content-day">
          <%=sp_payment.month.name%>
          <%=sp_payment.day.name %>
        </div>
        <%if sp_payment.medal!="0"%>
        <div class="comtent-medal">
          <%="#{sp_payment.medal}枚"%>
        </div>
        <%end%>
        <%if sp_payment.ball!="0"%>
        <div class="comtent-ball">
          <%="#{sp_payment.ball}玉"%>
        </div>
        <%end%>
        <div class="btns">
        <%= link_to '詳細', sp_payment_path(sp_payment.id),  id:'btn',class: 'btn' %>
        </div>
      </div>
    <%end%>
  </div>
</div>